apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: inference
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
  labels:
    app: cloudinferops-gateway
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cloudinferops-gateway
  type: ClusterIP
