apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudinferops-ui
  namespace: observability
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /cloudinferops
            pathType: Prefix
            backend:
              service:
                name: cloudinferops-ui
                port: {number: 80}
